name: default
on: 
  push:
    branches:    
      - master
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - README.md
    tags-ignore:
      - v*
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Tests
        run:  go test ./...

      - name: Get branch envs
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build
        env: 
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          GOOS=darwin GOARCH=amd64 make build RELEASE=$SOURCE_BRANCH OUTPUT=fcl_darwin_amd64
          GOOS=linux GOARCH=amd64 make build RELEASE=$SOURCE_BRANCH OUTPUT=fcl_linux_amd64